Better support for multiple machines and clean up structure

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -1,25 +1,32 @@
 #!/usr/bin/env bash
 set -e
+
+
 # TODO: Make interruptible/atomic
 # TODO: Use correct ssh port? (can change over a deploy)
+HOSTNAME=@hostname@
 HOST=@host@
 SYSTEM=@systembuild@
 SWITCH=@switch@
 
 SSH_OPTS="-o BatchMode=yes"
 
+# Prefix all output with host name
+# From https://unix.stackexchange.com/a/440439/214651
+exec > >(sed "s/^/[$HOSTNAME] /")
+exec 2> >(sed "s/^/[$HOSTNAME] /" >&2)
+
 # TODO: What about GC?
 # TODO: Generate hardware-config every time?
 
+echo "Copying closure to host.." >&2
+nix-copy-closure -s --to $HOST $SYSTEM $SWITCH
 
-echo "Copying closure to host.."
-nix-copy-closure -s --to ssh://$HOST $SYSTEM $SWITCH
-
-echo "Triggering system switcher.."
+echo "Triggering system switcher.." >&2
 id=$(ssh $SSH_OPTS $HOST "$SWITCH/bin/switch" start $SYSTEM)
 
 
-echo -n "Trying to confirm success"
+echo "Trying to confirm success.." >&2
 set +e
 prevstatus="unknown"
 prevactive=0
@@ -28,22 +35,19 @@ while [ "$active" != 0 ]; do
 	# TODO: Because of the imperative network-setup script, when e.g. the defaultGateway is removed, the previous entry is still persisted on a rebuild switch, even though with a reboot it wouldn't. Maybe use the more modern and declarative networkd to get around this
 	status=$(timeout 5 ssh -o ControlPath=none $SSH_OPTS $HOST "$SWITCH/bin/switch" active "$id")
 	active=$?
-	echo -n .
 	sleep 1
 done
 
-echo ""
-
 case "$status" in
 	"success")
-		echo "Successfully activated new system!"
+		echo "Successfully activated new system!" >&2
 		;;
 	"failure")
-		echo "Failed to activate new system! Rolled back to previous one"
+		echo "Failed to activate new system! Rolled back to previous one" >&2
 		# TODO: Try to show what failed
 		#ssh $SSH_OPTS $HOST cat /var/lib/system-switcher/system-$id/log
 		;;
 	*)
-	  echo "This shouldn't occur!"
+	  echo "This shouldn't occur!" >&2
 		;;
 esac
